### ISSUE TITLE
How to build AudioCurve?

### ISSUE THREAD

**Issue by dmbomer** [NatronGitHub/openfx-arena#3]
I have to ask.

**Comment by rodlie** [comment]
What is the problem? Note that users usually don't need to build these plugins as they are included in Natron.

**Comment by dmbomer** [comment]
I am trying to get AudioCurve

**Comment by rodlie** [comment]
Make sure you have libsox before build:

```
git clone https://github.com/NatronGitHub/openfx-arena
cd openfx-arena
git submodule update --init --recursive
cd Audio
make CONFIG=release
```

**Comment by dmbomer** [comment]
Done but for some strange reason Ubuntu has libsox3 and the steps provided failed.  Only after install libsox-dev did the last step make CONFIG=release complete.

**Comment by rodlie** [comment]
You always need the dev/devel packages when building from source.

**Comment by dmbomer** [comment]
Nice it worked.

Thank you Sir

So for the next person 

**Ubuntu 18.04.3 kernel 5 libsox-dev and pkg-config must be installed.**

OR you will get messages about pkg-config and sox

git clone https://github.com/NatronGitHub/openfx-arena
cd openfx-arena
git submodule update --init --recursive
cd Audio
make CONFIG=release

And then copy Linux-64-release folder to your .Natron folder in the home directory.

Point Natron to that directory
open Natron
Edit>preference>plugins>pyplug search path>add>folder .Natron/Linux-64-release
save
Restart Natron.

**Comment by rodlie** [comment]
You can see in https://github.com/NatronGitHub/openfx-arena/blob/master/.travis.yml for building on Ubuntu.
